import { Route, Routes } from "react-router-dom";
import { useState, useEffect } from "react";
import "./App.css";
import Header from "../Header/Header";
import Dashboard from "../Dashboard/Dashboard";
import Reviews from "../Reviews/Reviews";
import Review from "../Review/Review";
import AboutMe from "../AboutMe/AboutMe";
import AboutUs from "../AboutUs/AboutUs";
import MyStory from "../AboutMe/MyStory";
import Hobbies from "../AboutMe/Hobbies";
import Contact from "../AboutMe/Contact";
import SiteHistory from "../AboutUs/SiteHistory";
import SiteMission from "../AboutUs/SiteMission";

function App() {
  const [reviews, setReviews] = useState([]);

  useEffect(() => {
    fetch("https://api.nomoreparties.co/emoji-critic-ens")
      .then((res) => {
        if (res.ok) {
          return res.json();
        } else {
          return Promise.reject(error);
        }
      })
      .then((data) => {
        //Set the reviews state with the fetched data and pass it to the Reviews component as a prop
        setReviews(data);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);
  // The route for each individual review is generated dynamically. When you click on a link
  //in the list of reviews the URL is updated and and mapped to this special property
  //in the route path :reviewId. This special property is generated by the hook,
  // useParams() and is accessed in the Review component.
  return (
    <div className="App">
      <Header />
      <Routes>
        <Route path="/" element={<Dashboard />} />
        <Route path="/Reviews" element={<Reviews reviews={reviews} />} />
        <Route
          path="/Reviews/:reviewId"
          element={<Review reviews={reviews} />}
        />
        <Route path="/AboutMe" element={<AboutMe />}>
          <Route path="MyStory" element={<MyStory />} />
          <Route path="Hobbies" element={<Hobbies />} />
          <Route path="Contact" element={<Contact />} />
        </Route>
        <Route path="/AboutUs" element={<AboutUs />}>
          <Route path="SiteHistory" element={<SiteHistory />} />
          <Route path="SiteMission" element={<SiteMission />} />
        </Route>
      </Routes>
    </div>
  );
}

export default App;
